# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eric Crawford
email: eric [dot] crawford [at] cs.mcgill.ca
description: > # this means to ignore newlines until "baseurl:"
  Website of Eric Crawford, PhD student studying machine learning and theoretical neuroscience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://e2crawfo.github.io" # the base hostname & protocol for your site
github_username:  e2crawfo

# Build settings
markdown: kramdown
